name: Blog CI/CD # 脚本 workflow 名称

on:
  push:
    branches: [hexo] # 当监测 hexo 的 push
    paths: # 监测所有 source 目录下的文件变动，所有 yml,json 后缀文件的变动。
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  blog: # 任务名称
    timeout-minutes: 30 # 设置 30 分钟超时
    runs-on: ubuntu-latest # 指定最新 ubuntu 系统
    steps:
      - name: Checkout hexo branch
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or any specific version you need
      - name: Cache node_modules # 缓存 node_modules，提高编译速度，毕竟每月只有 2000 分钟。
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Init Node.js # 安装源代码所需插件
        run: |
          npm install
          echo "init node successful"
      - name: Install Hexo-cli # 安装 Hexo
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      - name: Build Blog # 编译创建静态博客文件
        run: |
          hexo clean
          hexo g
          echo "build blog successful"
      - name: Deploy Blog # 设置 git 信息并推送静态博客文件
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.CLI_TOKEN }}
        run: |
          git config --global user.name "lihaibo"
          git config --global user.email "haibofly@outlook.com"
          hexo deploy

      - run: echo "Deploy Successful!"
